### PR TITLE
ci updates w.r.t prow and aicoe-ci

### PR DESCRIPTION
**Pull request by harshad16**
ci updates w.r.t prow and aicoe-ci
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
Thanks!

**Comment by goern** [comment]
somehow sesheta is not adding labels @thoth-station/cyborg-supervisors

**Comment by harshad16** [comment]
This was blocked by the prow ci downtime.

**Pull request merged**
